import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Luxenta",
	description: "Generated by Luxenta",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" data-arp="">
			<body
				data-new-gr-c-s-check-loaded="14.1250.0"
				data-gr-ext-installed=""
				cz-shortcut-listen="true"
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Toaster richColors position="top-center" />
				{children}
			</body>
		</html>
	);
}
